name: Deploy to Hosting

on:
  push:
    branches: [ main ]  # Триггер на пуш в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      

      - name: Upload files to hosting via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOSTING_IP }}
          username: ${{ secrets.HOSTING_USER }}
          password: ${{ secrets.HOSTING_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "public/build/*"
          target: "/var/www/u1970687/data/www/trip-trove.ru/"
          strip_components: 0 
          overwrite: true
          debug: true
