name: Deploy to Hosting

on:
  push:
    branches: [ main ]  # Триггер на пуш в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов

        # - name: Setup PHP
        #   uses: shivammathur/setup-php@v2
        #   with:
        #     php-version: '8.2'
        #     extensions: mbstring, ctype, fileinfo, openssl, PDO, mysql, pdo_mysql, tokenizer, xml
        #     coverage: none

      - name: Download composer.phar
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=. --filename=composer.phar
          php composer.phar --version
      - name: Install dependencies with composer
        run: php composer.phar install --no-dev --prefer-dist --optimize-autoloader

        # - name: Setup Node.js
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: '18'

        # - name: Install npm dependencies
        #   run: npm ci && npm run build

        # - name: Prepare .env
        #   run: |
        #     cp .env.example .env
        #     php artisan key:generate

      - name: Upload files to hosting via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOSTING_IP }}
          username: ${{ secrets.HOSTING_USER }}
          password: ${{ secrets.HOSTING_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./"
          target: "/var/www/u1970687/data/www/trip-trove.ru/"
          strip_components: 1
      #     strip_components: 0
      #     overwrite: true
      #     debug: true
      # - name: List files before archiving
      #   run: |
      #     echo "Содержимое рабочей директории:"
      #     ls -R .
